### ISSUE TITLE
Update to use the latest config variables?

### ISSUE THREAD

**Issue by mhos** [dm0reau/automysqlbackup_hourly#1]
I know you haven't touched this script in some time but this would still be very useful to the community.
Do you think you could update this script to use with newer version of automysqlbackup?

The version im using doesn't have DOWEEKLY it has CONFIG_do_weekly options.

EX:
# Which day do you want monthly backups? (01 to 31)
# If the chosen day is greater than the last day of the month, it will be done
# on the last day of the month.
# Set to 0 to disable monthly backups.
#CONFIG_do_monthly="01"
CONFIG_do_monthly="0"

# Which day do you want weekly backups? (1 to 7 where 1 is Monday)
# Set to 0 to disable weekly backups.
#CONFIG_do_weekly="5"
CONFIG_do_weekly="7"

# Set rotation of daily backups. VALUE*24hours
# If you want to keep only today's backups, you could choose 1, i.e. everything older than 24hours will be removed.
#CONFIG_rotation_daily=6
CONFIG_rotation_daily=6

**Comment by dm0reau** [comment]
Hi,
Is this the default config for automysqlbackup packaged in Debian 10 and/or Ubuntu 20.04 ?

**Comment by mhos** [comment]
It's for Ubuntu 20.04.2 LTS

**Comment by dm0reau** [comment]
Ok thank you. I'll take a look at this.

**Comment by mhos** [comment]
Very cool Thank you. Great Idea by the way. I found a hacky way of just running the daily scripts every hour but would be nice to see it split out into the hourly vs just dumped in the daily folder.
Would be a great addition to the original code as well. Icing on the cake.

Thanks again for looking into this.

**Comment by dm0reau** [comment]
I have done some tests with packaged version of automysqlbackup with Debian 10 and Ubuntu 20.04, and everything works fine. Maybe it's not the case with automysqlbackup's original version hosted on Sourceforge, but I think it's better to keep compatibility with Debian & Ubuntu packages default config.
